name: CI/CD Workflow

on:
  push:
    branches:
      - int
      - tst
  pull_request:
    branches:
      - int
      - tst
    types:
      - closed
  create:
    tags:
      - prod-*
  workflow_dispatch:

jobs:
  build-image:
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/int' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'int' && github.actor != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: echo "hola build image"

  depoloy-test:
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/tst' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'tst' && github.actor != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: SWR Login
        run: echo "SWR login"
      - name: Docker Pull
        run: echo "Docker pull "
      - name: Retag Image
        run: echo "Retag Image to tst"

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest
    steps:
      - name: SWR Login
        run: echo "SWR login"
      - name: Docker Pull
        run: echo "Docker pull "
      - name: Retag Image
        run: echo "Retag Image to prd"
