name: CI/CD Workflow

on:
  push:
    branches:
      - int
      - tst
      - dev-cicd

  create:
    tags:
      - prod-*
  workflow_dispatch:

jobs:
  build-image:
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/int' || github.event_name == 'push' && github.ref == 'refs/heads/dev-cicd'
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: echo "hola build image"

  depoloy-test:
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/tst' 
    runs-on: ubuntu-latest
    steps:
      - name: SWR Login
        run: echo "SWR login"
      - name: Docker Pull
        run: echo "Docker pull "
      - name: Retag Image
        run: echo "Retag Image to tst"

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest
    steps:
      - name: SWR Login
        run: echo "SWR login"
      - name: Docker Pull
        run: echo "Docker pull "
      - name: Retag Image
        run: echo "Retag Image to prd"
