on:
  push:
    branches:
      - dev-cicd
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-step.outputs.image }}
    steps:
      - name: Run Build
        id: build-step
        uses: teranjoan/jtgatests/build@dev-cicd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      BUILDED_IMAGE: ${{ needs.build.outputs.image }}
    steps:
      - name: Run Deploy
        uses: teranjoan/jtgatests/deploy@dev-cicd

      - name: Print Image
        run: echo $BUILDED_IMAGE
